In [ ]:
from si.io.csv_file import read_csv
from si.model_selection.split import stratified_train_test_split

import numpy as np
import pandas as pd
from si.data.dataset import Dataset

### EX 1.1

In [9]:
dataset = read_csv("../datasets/iris/iris.csv", sep = ",", features = True, label = True )

### EX 1.2

In [10]:
penul_var = dataset.X[:,-2]

print(penul_var.shape)

(150,)


### EX 1.3

In [20]:
last_10_sample = dataset.X[-10:]

print(last_10_sample)

np.nanmean(last_10_sample, axis=0)


[[6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]


array([6.45, 3.03, 5.33, 2.17])

### EX 1.4

In [66]:
less_equal_6 = np.all(dataset.X <= 6, axis=1) 

print(np.count_nonzero(less_equal_6==True))




89


### EX 1.5

In [ ]:
mask = dataset.y !='Iris-setosa'

print(np.count_nonzero(dataset.y[mask]))

100


### EX 6.2 - Test the "stratified_train_test_split" function with the iris dataset.

In [ ]:
import pandas as pd
import numpy as np
from si.data.dataset import Dataset
from si.model_selection.split import stratified_train_test_split

# 1. Load the iris.csv (adapt path if needed)
# Example uses standard iris CSV format with columns: sepal.length, sepal.width, petal.length, petal.width, class
df = pd.read_csv("iris.csv")  # Make sure "iris.csv" is in your working directory

# 2. Separate features and labels
# Adjust column names to match your CSV format
X = df.drop("class", axis=1).to_numpy()
y = df["class"].to_numpy()
features = df.drop("class", axis=1).columns.tolist()
label = "class"

# 3. Wrap in your Dataset object
iris_dataset = Dataset(X, y, features, label)

# 4. Split using your function
train, test = stratified_train_test_split(iris_dataset, test_size=0.2, random_state=42)

# 5. Print class distribution to check stratification
train_classes, train_counts = np.unique(train.y, return_counts=True)
test_classes, test_counts = np.unique(test.y, return_counts=True)

print("Train set class distribution:")
for cls, count in zip(train_classes, train_counts):
    print(f"{cls}: {count}")
    
print("\nTest set class distribution:")
for cls, count in zip(test_classes, test_counts):
    print(f"{cls}: {count}")

print("\nTrain size:", len(train.y))
print("Test size:", len(test.y))
