In [13]:
from si.io.csv_file import read_csv
import numpy as np

### EX 1.1

In [9]:
dataset = read_csv("../datasets/iris/iris.csv", sep = ",", features = True, label = True )

### EX 1.2

In [10]:
penul_var = dataset.X[:,-2]

print(penul_var.shape)

(150,)


### EX 1.3

In [20]:
last_10_sample = dataset.X[-10:]

print(last_10_sample)

np.nanmean(last_10_sample, axis=0)


[[6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]


array([6.45, 3.03, 5.33, 2.17])

### EX 1.4

In [66]:
less_equal_6 = np.all(dataset.X <= 6, axis=1) 

print(np.count_nonzero(less_equal_6==True))




89


### EX 1.5

In [ ]:
mask = dataset.y !='Iris-setosa'

print(np.count_nonzero(dataset.y[mask]))

100
